services:

  postgres:
    image: postgres:17
    container_name: student-management-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: studentdb

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d studentdb"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - student-network

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: student-management-api-container
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/studentdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - student-network

volumes:
  postgres_data:

networks:
  student-network:
    driver: bridge